name: Create Release

on:
  push:
    branches:
      - main

    paths:
      - 'src/manifest.json'

  workflow_dispatch: # allows to manually trigger the workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo command
        run: echo "We're up and running!"
    
      - name: Echo git status
        run: git status

      - name: output current version
        run: |
          version=$(jq -r '.version' src/manifest.json)
          echo "Current version: $version"
    
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(jq -r '.version' src/manifest.json)
          echo "Building release $version"
          ./build.sh $version
          echo "Built release $version"
          echo "Extract release notes from CHANGELOG.md"
          # sed -n "/## \[v${version}\]/,/## /p" CHANGELOG.md | sed '$d' > release-notes-${version}.md
          sed -n "/## \[v${version}\]/,/^## /p" CHANGELOG.md | sed '1d;$d' > release-notes-${version}-content.md
          echo "## Changes" >> release-notes-${version}.md
          cat release-notes-${version}-content.md >> release-notes-${version}.md
          echo "Extracted release notes from CHANGELOG.md"
          echo "Creating release $version"
          gh release create v${version} build/gh-actions-test-${version}.xpi -t "v${version}" --notes-file release-notes-${version}.md
          echo "Created release $version"