name: Create Release

on:
  push:
    branches:
      - main

    paths:
      - 'src/manifest.json'

  workflow_dispatch: # allows to manually trigger the workflow_dispatch

env:
  BUILD_BASENAME: gh-actions-test
  VERSION: x.x.x # add this only to satify the linter

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: |
          sudo apt install jq
      
      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(jq -r '.version' src/manifest.json)

          # Build release
          echo "Building release ${BUILD_BASENAME}-$version"
          ./build.sh ${BUILD_BASENAME} $version
          echo "Built release ${BUILD_BASENAME}-$version"

          # Change notes
          echo "Extract release notes from CHANGELOG.md"
          echo "## Changes" >> release-notes-${version}.md
          sed -n "/## \[v${version}\]/,/^## /p" CHANGELOG.md | sed '1d;$d' >> release-notes-${version}.md
          echo "Extracted release notes from CHANGELOG.md"
          
          # Create release
          echo "Creating release $version"
          gh release create v${version} build/${BUILD_BASENAME}-${version}.xpi -t "v${version}" --notes-file release-notes-${version}.md
          echo "Created release $version"
