name: Release Workflow

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Create new branch
      run: |
        git checkout -b version-bump

    - name: Append timestamp to README.md
      run: |
        echo "\nTimestamp: $(date)" >> README.md

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Append timestamp to README.md"

    - name: Push changes and create PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin version-bump
    
    - name: Push changes and create PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh pr create --title "Update README with timestamp" --body "This PR appends the current timestamp to the README file."
