name: Vars Test

on:
  workflow_dispatch: # allows to manually trigger the workflow_dispatch

env:
  ASSET_NAME: asset.xpi
  
jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version number
        id: extract_version
        run: echo "VERSION=$(jq -r '.version' src/manifest.json)" >> $GITHUB_ENV
      
      - name: Tell Version
        run: |
          echo ${{ env.VERSION }}

      - name: Asset Name
        run: |
          echo ${{ env.ASSET_NAME }} 